# Go to each of these sites and do a job search with whichever parameters you want.  Copy the URL you get and replace the ones below. I've only developed scrapers for the three sites so far.  The script will ideally run every day so try to limit job postings to the last 24 hours
URLs = [
    "https://www.ziprecruiter.com/candidate/search?radius=5000&days=1&search=Python+-senior+-devops+-etl+-j2ee+-%22data+engineer%22+-%22data+scientist%22+-%22technical+writer%22+-wix+-%22systems+engineer%22+-FPGA+-director+-principal+-%22reliability+engineer%22&location=Omaha%2C+NE",
    "https://www.linkedin.com/jobs/search/?f_E=1%2C2%2C3&f_LF=f_AL&f_TPR=r86400&geoId=103644278&keywords=python%20developer%20-senior%20-sr%20-mid-senior&location=United%20States",
    "https://www.python.org/jobs/",
]

# "https://www.linkedin.com/jobs/search/?f_E=1%2C2%2C3&f_LF=f_AL&f_TPR=r604800&geoId=103644278&keywords=python%20developer%20-senior%20-sr%20-mid-senior&location=United%20States",

# Customize the following terms and scores where positive traits correlate with positive numbers and negative with negative numbers.  The job listings will be "scored" and the 10 best will be e-mailed to you.
searchPhrases = {
    "Entry level": 50,
    "Flask": 25,
    "Junior": 25,
    "Jr": 25,
    "Portland": 10,
    "Oregon": 10,
    ", OR": 10,
    "Eugene": 10,
    "San Francisco": 10,
    "Los Angeles": 10,
    "Santa Monica": 10,
    "Marina del Rey": 10,
    "Venice": 10,
    "Long Beach": 10,
    "Pasadena": 10,
    "Irvine": 10,
    "Silicon Valley": 10,
    "San Jose": 10,
    "California": 10,
    ", CA": 10,
    "Seattle": 10,
    "Washington": 10,
    ", WA": 10,
    "New York": 10,
    "NYC": 10,
    "No longer accepting applications": -1000,
    "You applied on": -1000,
    "Battery Engineer": -100,
    "active TS clearance": -100,
    "Staff Backend Engineer": -100,
    "8+": -100,
    "8 years": -100,
    "Lead Python Developer": -50,
    "Lead Developer": -50,
    "Lead Software Developer": -50,
    "Lead Software Engineer": -50,
    "Technology Lead": -50,
    "Network Architect": -50,
    "Cloud Technical Solutions Engineer": -50,
    "Ruby on Rails Fullstack Engineer": -50,
    "Ruby on Rails Developer": -50,
    "Clearance": -50,
    "Active SECRET": -50,
    "7+": -50,
    "6+": -50,
    "5+": -50,
    "7 years": -50,
    "6 years": -50,
    "5 years": -50,
    "Minimum of 5": -50,
    "Mid-Level": -50,
    "Mid-Senior": -50,
    "Senior Python": -50,
    "Senior Data": -50,
    "Senior Full Stack": -50,
    "Senior Backend": -50,
    "Microsoft Dynamics": -50,
    "Hardware Technician": -50,
    "Linux System administrator": -50,
    "Embedded Software": -50,
    "Engineer III": -50,
    "Engineer IV": -50,
    "Engineer V": -50,
    "Engineer VI": -50,
    "Engineer VII": -50,
    "Principal Software": -50,
    "Security Engineer": -50,
    "Senior DevOps": -50,
    "Systems Engineering": -25,
    "Solutions Engineer": -25,
    "Network Developer": -25,
    "Network Engineer": -25,
    "Data Engineer": -25,
    "Data Science": -25,
    "Talend": -25,
    "ERP": -25,
    "4+": -25,
    "Front End Developer": -25,
    "Frontend Web": -25,
    "Fintech": -25,
    "Trading": -25,
    "Wall Street": -25,
    "DevOps": -25,
    "Qlik": -25,
    "Engineer Infrastructure": -25,
    "Cloud engineer": -25,
    "AWS Lead": -25,
    "Computer Scientist": -25,
    "3-5 years": -25,
    "Application Development": -10,
    "Blockchain": -10,
    "Crypto": -10,
    "Quant": -10,
    "ETL Developer": -10,
    "React": -10,
    "React Native": -10,
    "C++": -10,
    "PHP": -10,
    "Trading": -10,
    "Hedge Fund": -10,
    "Java": -10,
    "Jr.Java": -10,
    "Web Developer": -10,
    "WordPress": -10,
    "Shopify": -10,
    "3-4 years": -10,
    "Engineer II": -10,
    "Sports Betting": -10,
    "Developer Mobile App": -10,
    "Container": -10,
    "Embedded": -10,
    "React": -5,
    "Vue": -5,
    "Angular": -5,
    "Cassandra": -5,
    "Node": -5,
    ".NET": -5,
    "JavaScript Developer": -5,
}
